"""
Static reference lists of K-12 school districts by state.

Used to generate targeted per-district search queries that surface staff
directory pages more reliably than generic state-level search phrasing alone.
"""

from __future__ import annotations

# Town and regional district names for Connecticut (~169 municipalities plus
# regional school districts). Search queries use the short town/district name
# (e.g. "Brookfield") rather than the full legal district name.
CONNECTICUT_DISTRICTS: tuple[str, ...] = (
    "Andover",
    "Ansonia",
    "Ashford",
    "Avon",
    "Barkhamsted",
    "Berlin",
    "Bethany",
    "Bethel",
    "Bethlehem",
    "Bloomfield",
    "Bolton",
    "Bozrah",
    "Branford",
    "Bridgeport",
    "Bridgewater",
    "Bristol",
    "Brookfield",
    "Brooklyn",
    "Burlington",
    "Canaan",
    "Canterbury",
    "Canton",
    "Chaplin",
    "Cheshire",
    "Chester",
    "Clinton",
    "Colchester",
    "Colebrook",
    "Columbia",
    "Cornwall",
    "Coventry",
    "Cromwell",
    "Danbury",
    "Darien",
    "Deep River",
    "Derby",
    "Durham",
    "East Granby",
    "East Haddam",
    "East Hampton",
    "East Hartford",
    "East Lyme",
    "East Windsor",
    "Easton",
    "Ellington",
    "Enfield",
    "Essex",
    "Fairfield",
    "Farmington",
    "Franklin",
    "Glastonbury",
    "Goshen",
    "Granby",
    "Greenwich",
    "Griswold",
    "Groton",
    "Guilford",
    "Haddam",
    "Hamden",
    "Hampton",
    "Hartford",
    "Hartland",
    "Harwinton",
    "Hebron",
    "Kent",
    "Killingly",
    "Killingworth",
    "Lebanon",
    "Ledyard",
    "Lisbon",
    "Litchfield",
    "Lyme",
    "Madison",
    "Manchester",
    "Mansfield",
    "Marlborough",
    "Meriden",
    "Middlebury",
    "Middletown",
    "Milford",
    "Monroe",
    "Montville",
    "Morris",
    "Naugatuck",
    "New Britain",
    "New Canaan",
    "New Fairfield",
    "New Hartford",
    "New Haven",
    "New London",
    "New Milford",
    "Newington",
    "Newtown",
    "Norfolk",
    "North Branford",
    "North Canaan",
    "North Haven",
    "North Stonington",
    "Norwalk",
    "Norwich",
    "Old Lyme",
    "Old Saybrook",
    "Orange",
    "Oxford",
    "Plainfield",
    "Plainville",
    "Plymouth",
    "Pomfret",
    "Portland",
    "Preston",
    "Prospect",
    "Putnam",
    "Redding",
    "Ridgefield",
    "Rocky Hill",
    "Roxbury",
    "Salem",
    "Salisbury",
    "Scotland",
    "Seymour",
    "Sharon",
    "Shelton",
    "Sherman",
    "Simsbury",
    "Somers",
    "South Windsor",
    "Southbury",
    "Southington",
    "Sprague",
    "Stafford",
    "Stamford",
    "Stonington",
    "Stratford",
    "Suffield",
    "Thomaston",
    "Thompson",
    "Tolland",
    "Torrington",
    "Trumbull",
    "Union",
    "Vernon",
    "Voluntown",
    "Wallingford",
    "Warren",
    "Washington",
    "Waterbury",
    "Waterford",
    "Watertown",
    "West Hartford",
    "West Haven",
    "Westbrook",
    "Weston",
    "Westport",
    "Wethersfield",
    "Willington",
    "Wilton",
    "Winchester",
    "Windham",
    "Windsor",
    "Windsor Locks",
    "Wolcott",
    "Woodbridge",
    "Woodbury",
    "Woodstock",
    "Regional School District 1",
    "Regional School District 4",
    "Regional School District 5",
    "Regional School District 7",
    "Regional School District 8",
    "Regional School District 9",
    "Regional School District 10",
    "Regional School District 11",
    "Regional School District 12",
    "Regional School District 13",
    "Regional School District 14",
    "Regional School District 15",
    "Regional School District 16",
    "Regional School District 17",
    "Regional School District 18",
    "Regional School District 19",
    "Regional School District 20",
)

NEW_YORK_DISTRICTS: tuple[str, ...] = (
    "New York City",
    "Buffalo",
    "Yonkers",
    "Rochester",
    "Syracuse",
    "Brentwood",
    "Newburgh",
    "Wappingers",
    "Greece",
    "East Ramapo",
    "New Rochelle",
    "Williamsville",
    "Middle Country",
    "Shenendehowa",
    "Utica",
    "William Floyd",
    "Schenectady",
    "Longwood",
    "Albany",
    "North Syracuse",
    "Webster",
    "Smithtown",
    "Central Islip",
    "North Rockland",
    "Sewanhaka",
    "Arlington",
    "Clarkstown",
    "East Meadow",
    "Middletown",
    "Patchogue-Medford",
    "Half Hollow Hills",
    "Levittown",
    "Niagara Falls",
    "Mount Vernon",
    "Syosset",
    "Great Neck",
    "Liverpool",
    "White Plains",
    "Monroe-Woodbury",
    "Massapequa",
    "Kenmore-Tonawanda",
    "Freeport",
    "Kingston",
    "Uniondale",
    "West Seneca",
    "Hempstead",
    "North Colonie",
    "Saratoga Springs",
    "Bay Shore",
    "South Huntington",
)

NEW_JERSEY_DISTRICTS: tuple[str, ...] = (
    "Newark Public Schools",
    "Elizabeth",
    "Jersey City",
    "Paterson",
    "Edison",
    "Trenton",
    "Toms River",
    "Woodbridge",
    "Union City",
    "Passaic",
    "Hamilton",
    "Clifton",
    "Cherry Hill",
    "Perth Amboy",
    "Freehold Regional",
    "Vineland",
    "Bayonne",
    "Plainfield",
    "New Brunswick",
    "East Orange",
    "West Windsor-Plainsboro",
    "Middletown",
    "Brick",
    "East Brunswick",
    "Old Bridge",
    "Bridgewater-Raritan",
    "West New York",
    "South Brunswick",
    "Union Township",
    "Wayne",
    "Irvington",
    "Jackson",
    "Egg Harbor Township",
    "Piscataway",
    "Franklin Township",
    "Hillsborough",
    "North Bergen",
    "Washington Township",
    "Camden",
    "Parsippany-Troy Hills",
    "Monroe Township",
    "West Orange",
    "South Orange-Maplewood",
    "Gloucester Township",
    "Lenape Regional",
    "Atlantic City",
    "Sayreville",
    "Livingston",
    "Bloomfield",
    "Bridgeton",
)

CALIFORNIA_DISTRICTS: tuple[str, ...] = (
    "Los Angeles Unified",
    "San Diego Unified",
    "Fresno Unified",
    "Long Beach Unified",
    "Elk Grove Unified",
    "Corona-Norco Unified",
    "San Francisco Unified",
    "San Bernardino City Unified",
    "Clovis Unified",
    "Kern High School District",
    "Capistrano Unified",
    "Riverside Unified",
    "Sacramento City Unified",
    "Garden Grove Unified",
    "San Juan Unified",
    "Irvine Unified",
    "Sweetwater Union High School District",
    "Stockton Unified",
    "Poway Unified",
    "Oakland Unified",
    "Fontana Unified",
    "Fremont Unified",
    "Moreno Valley Unified",
    "San Ramon Valley Unified",
    "Mt. Diablo Unified",
    "Visalia Unified",
    "Bakersfield City",
    "Anaheim Union High School District",
    "Lodi Unified",
    "Temecula Valley Unified",
    "Desert Sands Unified",
    "West Contra Costa Unified",
    "Chino Valley Unified",
    "San Jose Unified",
    "Orange Unified",
    "Manteca Unified",
    "Glendale Unified",
    "Rialto Unified",
    "Twin Rivers Unified",
    "Saddleback Valley Unified",
    "Chaffey Joint Union High School District",
    "Placentia-Yorba Linda Unified",
    "Hesperia Unified",
    "Hemet Unified",
    "Murrieta Valley Unified",
    "Downey Unified",
    "Chula Vista Elementary School District",
    "Antelope Valley Union High School District",
    "Tustin Unified",
    "Torrance Unified",
    "Pomona Unified",
    "East Side Union High School District",
    "Palm Springs Unified",
    "William S. Hart Union High School District",
    "Lake Elsinore Unified",
)

MASSACHUSETTS_DISTRICTS: tuple[str, ...] = (
    "Boston",
    "Worcester",
    "Springfield",
    "Lynn",
    "Brockton",
    "Lowell",
    "Lawrence",
    "New Bedford",
    "Newton",
    "Fall River",
    "Quincy",
    "Framingham",
    "Taunton",
    "Haverhill",
    "Revere",
    "Everett",
    "Plymouth",
    "Brookline",
    "Lexington",
    "Wachusett",
    "Cambridge",
    "Chicopee",
    "Methuen",
    "Malden",
    "Chelsea",
    "Leominster",
    "Arlington",
    "Peabody",
    "Attleboro",
    "Shrewsbury",
    "Waltham",
    "Weymouth",
    "Needham",
    "Andover",
    "Bridgewater-Raynham",
    "Natick",
    "Braintree",
    "Fitchburg",
    "Acton-Boxborough",
    "Chelmsford",
    "Holyoke",
    "Pittsfield",
    "Westfield",
    "Somerville",
    "Billerica",
    "Barnstable",
    "Marlborough",
    "Franklin",
    "Westford",
    "Beverly",
)

TEXAS_DISTRICTS: tuple[str, ...] = (
    "Houston ISD",
    "Dallas ISD",
    "Cypress-Fairbanks ISD",
    "Northside ISD",
    "Katy ISD",
    "Fort Bend ISD",
    "Austin ISD",
    "Conroe ISD",
    "Fort Worth ISD",
    "Frisco ISD",
    "Aldine ISD",
    "North East ISD",
    "Arlington ISD",
    "Klein ISD",
    "Garland ISD",
    "El Paso ISD",
    "Lewisville ISD",
    "Plano ISD",
    "Humble ISD",
    "Pasadena ISD",
    "Socorro ISD",
    "Round Rock ISD",
    "San Antonio ISD",
    "Killeen ISD",
    "Lamar CISD",
    "Leander ISD",
    "United ISD",
    "Clear Creek ISD",
    "Alief ISD",
    "Mesquite ISD",
    "Brownsville ISD",
    "Richardson ISD",
    "Ysleta ISD",
    "Mansfield ISD",
    "Spring ISD",
    "Keller ISD",
    "Edinburg CISD",
    "Spring Branch ISD",
    "Corpus Christi ISD",
    "Ector County ISD",
    "Denton ISD",
    "Irving ISD",
    "Amarillo ISD",
    "Pharr-San Juan-Alamo ISD",
    "Northwest ISD",
    "Alvin ISD",
    "Comal ISD",
    "Midland ISD",
    "Grand Prairie ISD",
    "Judson ISD",
    "Pflugerville ISD",
    "Lubbock ISD",
    "Prosper ISD",
    "La Joya ISD",
)

FLORIDA_DISTRICTS: tuple[str, ...] = (
    "Miami-Dade",
    "Broward",
    "Hillsborough",
    "Orange County",
    "Palm Beach",
    "Duval",
    "Polk",
    "Lee County",
    "Pinellas",
    "Pasco",
    "Brevard",
    "Osceola",
    "Seminole",
    "Volusia",
    "Manatee",
    "St. Johns",
    "Collier",
    "Lake County",
    "St. Lucie",
    "Sarasota",
    "Marion",
    "Clay",
    "Escambia",
    "Okaloosa",
    "Leon",
    "Santa Rosa",
    "Alachua",
    "Bay County",
    "Hernando",
    "Martin",
    "Indian River",
    "Charlotte",
    "Citrus",
    "Hendry",
    "Flagler",
    "Nassau",
    "Highlands",
    "Walton",
    "Putnam",
    "Columbia",
    "Sumter",
    "Monroe",
    "Okeechobee",
    "Jackson County",
    "Suwannee",
    "Levy",
    "Wakulla",
    "Baker",
    "Hardee",
    "Gadsden",
    "DeSoto",
    "Washington",
    "Holmes",
    "Bradford",
)

PENNSYLVANIA_DISTRICTS: tuple[str, ...] = (
    "Philadelphia",
    "Pittsburgh",
    "Central Bucks",
    "Reading",
    "Allentown",
    "Downingtown Area",
    "Bethlehem Area",
    "North Penn",
    "Upper Darby",
    "Central Dauphin",
    "Hazleton Area",
    "West Chester Area",
    "Council Rock",
    "Erie",
    "Lancaster",
    "Cumberland Valley",
    "Parkland",
    "Pennsbury",
    "Neshaminy",
    "Chambersburg Area",
    "Scranton",
    "Abington",
    "Lower Merion",
    "North Allegheny",
    "Pocono Mountain",
    "Easton Area",
    "East Penn",
    "Spring-Ford Area",
    "Wilkes-Barre Area",
    "Norristown Area",
    "West Shore",
    "Seneca Valley",
    "Altoona Area",
    "Hempfield",
    "Tredyffrin-Easttown",
    "State College Area",
    "Boyertown Area",
    "Haverford Township",
    "Pennridge",
    "Millcreek Township",
    "Harrisburg",
    "Wilson",
    "East Stroudsburg Area",
    "Dallastown Area",
    "Bensalem Township",
    "Souderton Area",
    "Bristol Township",
    "York City",
    "Butler Area",
    "Manheim Township",
    "Central York",
)

ILLINOIS_DISTRICTS: tuple[str, ...] = (
    "Chicago Public Schools",
    "School District U-46",
    "Rockford",
    "Indian Prairie",
    "Plainfield",
    "CUSD 300",
    "CUSD 308",
    "Naperville",
    "Valley View",
    "Schaumburg",
    "Waukegan",
    "Springfield",
    "Peoria",
    "Aurora East",
    "Unit 5",
    "Township High School District 211",
    "Township High School District 214",
    "St Charles CUSD 303",
    "CUSD 200",
    "Aurora West",
    "Palatine CCSD 15",
    "Champaign",
    "Joliet PSD 86",
    "Cicero SD 99",
    "Huntley",
    "Elmhurst",
    "Barrington",
    "Morton HSD 201",
    "Decatur",
    "Glenbard",
    "Cons HSD 230",
    "Belvidere",
    "Edwardsville",
    "Moline",
    "Crystal Lake",
    "Yorkville",
    "Joliet THSD 204",
    "DeKalb",
    "Lincoln-Way",
    "Evanston",
    "Quincy",
    "Round Lake",
    "Rock Island",
    "Maine Township HSD 207",
    "Harlem",
    "Woodstock",
    "Collinsville",
    "Wheeling CCSD 21",
    "Granite City",
    "Alton",
    "CCSD 59",
)

OHIO_DISTRICTS: tuple[str, ...] = (
    "Columbus City Schools",
    "Cincinnati Public Schools",
    "Cleveland Metropolitan",
    "Olentangy Local",
    "Toledo",
    "South-Western City",
    "Akron",
    "Lakota Local",
    "Dublin City",
    "Hilliard City",
    "Westerville City",
    "Dayton",
    "Pickerington Local",
    "Worthington City",
    "Mason City",
    "Fairfield City",
    "Hamilton City",
    "Parma City",
    "Northwest Local",
    "Centerville City",
    "Beavercreek City",
    "West Clermont Local",
    "Gahanna-Jefferson City",
    "Canton City",
    "Kettering City",
    "Sylvania",
    "Oak Hills Local",
    "Reynoldsburg City",
    "Mentor Exempted Village",
    "Willoughby-Eastlake City",
    "Forest Hills Local",
    "Springfield City",
    "Washington Local",
    "Upper Arlington City",
    "Milford Exempted Village",
    "Lancaster City",
    "Groveport Madison Local",
    "Brunswick City",
    "Medina City",
    "Middletown City",
    "Springboro Community City",
    "Plain Local",
    "Jackson Local",
    "Lorain City",
    "Princeton City",
    "Newark City",
    "Huber Heights City",
    "Elyria City",
    "Strongsville City",
    "Sycamore Community City",
)

GEORGIA_DISTRICTS: tuple[str, ...] = (
    "Gwinnett County",
    "Cobb County",
    "DeKalb County",
    "Fulton County",
    "Forsyth County",
    "Clayton County",
    "Atlanta Public Schools",
    "Henry County",
    "Cherokee County",
    "Savannah-Chatham County",
    "Paulding County",
    "Houston County",
    "Muscogee County",
    "Richmond County",
    "Columbia County",
    "Hall County",
    "Douglas County",
    "Coweta County",
    "Bibb County",
    "Fayette County",
    "Newton County",
    "Carroll County",
    "Rockdale County",
    "Barrow County",
    "Walton County",
    "Effingham County",
    "Bartow County",
    "Dougherty County",
    "Glynn County",
    "Clarke County",
    "Whitfield County",
    "Troup County",
    "Bulloch County",
    "Lowndes County",
    "Liberty County",
    "Catoosa County",
    "Bryan County",
    "Jackson County",
    "Griffin-Spalding County",
    "Camden County",
    "Floyd County",
    "Colquitt County",
    "Marietta City",
    "Oconee County",
    "Walker County",
    "Valdosta City",
    "Gainesville City",
    "Polk County",
    "Dalton Public Schools",
    "Coffee County",
)

NORTH_CAROLINA_DISTRICTS: tuple[str, ...] = (
    "Wake County",
    "Charlotte-Mecklenburg",
    "Guilford County",
    "Winston-Salem/Forsyth County",
    "Cumberland County",
    "Union County",
    "Johnston County",
    "Cabarrus County",
    "Durham Public Schools",
    "Gaston County",
    "Onslow County",
    "New Hanover County",
    "Pitt County",
    "Alamance-Burlington",
    "Buncombe County",
    "Robeson County",
    "Iredell-Statesville",
    "Harnett County",
    "Rowan-Salisbury",
    "Davidson County",
    "Wayne County",
    "Catawba County",
    "Randolph County",
    "Nash County",
    "Cleveland County",
    "Moore County",
    "Brunswick County",
    "Henderson County",
    "Craven County",
    "Burke County",
    "Lincoln County",
    "Chapel Hill-Carrboro",
    "Rockingham County",
    "Pender County",
    "Caldwell County",
    "Wilson County",
    "Duplin County",
    "Lee County",
    "Chatham County",
    "Hoke County",
    "Wilkes County",
    "Stanly County",
    "Lenoir County",
    "Carteret County",
    "Sampson County",
    "Franklin County",
    "Rutherford County",
    "Surry County",
    "Orange County",
    "Granville County",
    "Richmond County",
)

MICHIGAN_DISTRICTS: tuple[str, ...] = (
    "Detroit Public Schools",
    "Utica Community Schools",
    "Dearborn",
    "Ann Arbor",
    "Plymouth-Canton",
    "Rochester",
    "Chippewa Valley",
    "Grand Rapids",
    "Livonia",
    "Warren Consolidated",
    "Troy",
    "Kalamazoo",
    "Walled Lake",
    "Lansing",
    "Wayne-Westland",
    "L'anse Creuse",
    "Kentwood",
    "Forest Hills",
    "Farmington",
    "Traverse City",
    "Portage",
    "South Lyon",
    "Huron Valley",
    "Grand Blanc",
    "Rockford",
    "Clarkston",
    "Midland",
    "Birmingham",
    "Port Huron",
    "Northville",
    "Waterford",
    "Howell",
    "Lake Orion",
    "Hudsonville",
    "Novi",
    "West Ottawa",
    "Grosse Pointe",
    "Bay City",
    "Zeeland",
    "Brighton",
    "Oxford",
    "Woodhaven-Brownstown",
    "Davison",
    "Grandville",
    "Anchor Bay",
    "Taylor",
    "Grand Haven",
    "Saginaw",
    "Jenison",
    "Romeo",
)

VIRGINIA_DISTRICTS: tuple[str, ...] = (
    "Fairfax County",
    "Prince William County",
    "Loudoun County",
    "Virginia Beach",
    "Chesterfield County",
    "Henrico County",
    "Chesapeake",
    "Stafford County",
    "Arlington County",
    "Norfolk",
    "Newport News",
    "Spotsylvania County",
    "Richmond",
    "Hampton",
    "Hanover County",
    "Alexandria",
    "Suffolk",
    "Frederick County",
    "Albemarle County",
    "Roanoke County",
    "Roanoke City",
    "Portsmouth",
    "York County",
    "Rockingham County",
    "Williamsburg-James City County",
    "Fauquier County",
    "Augusta County",
    "Montgomery County",
    "Bedford County",
    "Culpeper County",
    "Pittsylvania County",
    "Campbell County",
    "Lynchburg",
    "Manassas City",
    "Henry County",
    "Washington County",
    "Harrisonburg",
    "Franklin County",
    "Prince George County",
    "Wise County",
    "Danville",
    "Shenandoah County",
    "Isle of Wight County",
    "Tazewell County",
    "Louisa County",
    "Warren County",
    "Gloucester County",
    "Orange County",
    "Accomack County",
    "Halifax County",
)

WASHINGTON_DISTRICTS: tuple[str, ...] = (
    "Seattle",
    "Lake Washington",
    "Spokane",
    "Tacoma",
    "Kent",
    "Puyallup",
    "Northshore",
    "Evergreen",
    "Vancouver",
    "Federal Way",
    "Bethel",
    "Edmonds",
    "Everett",
    "Issaquah",
    "Kennewick",
    "Bellevue",
    "Pasco",
    "Highline",
    "Auburn",
    "Yakima",
    "Renton",
    "Mukilteo",
    "North Thurston",
    "Central Valley",
    "Richland",
    "Clover Park",
    "Battle Ground",
    "Bellingham",
    "Central Kitsap",
    "Sumner-Bonney Lake",
    "Mead",
    "Marysville",
    "Lake Stevens",
    "Olympia",
    "Shoreline",
    "Snohomish",
    "South Kitsap",
    "Tahoma",
    "Peninsula",
    "Moses Lake",
    "Franklin Pierce",
    "Wenatchee",
    "Camas",
    "Snoqualmie Valley",
    "Mount Vernon",
    "Tumwater",
    "Sunnyside",
    "Longview",
    "Eastmont",
    "Omak",
)

ARIZONA_DISTRICTS: tuple[str, ...] = (
    "Mesa",
    "Chandler",
    "Tucson",
    "Peoria",
    "Gilbert",
    "Deer Valley",
    "Paradise Valley",
    "Phoenix Union",
    "Dysart",
    "Scottsdale",
    "Washington Elementary",
    "Glendale Union",
    "Sunnyside",
    "Vail",
    "Kyrene",
    "Cartwright",
    "Queen Creek",
    "Tolleson Union",
    "Higley",
    "Marana",
    "Tempe Union",
    "Amphitheater",
    "Yuma Union",
    "Litchfield Elementary",
    "Tempe Elementary",
    "Alhambra Elementary",
    "Agua Fria Union",
    "Glendale Elementary",
    "Yuma Elementary",
    "Florence",
    "Flagstaff",
    "Maricopa",
    "Pendergast",
    "Laveen",
    "Roosevelt",
    "Kingman",
    "Casa Grande Elementary",
    "Sahuarita",
    "Crane",
    "Avondale",
    "Littleton Elementary",
    "Madison Elementary",
    "Buckeye Elementary",
    "Nogales",
    "Humboldt",
    "Lake Havasu",
    "Flowing Wells",
    "Buckeye Union",
    "Catalina Foothills",
    "Phoenix Elementary",
    "Gadsden",
)

TENNESSEE_DISTRICTS: tuple[str, ...] = (
    "Memphis-Shelby County",
    "Davidson County",
    "Knox County",
    "Rutherford County",
    "Hamilton County",
    "Williamson County",
    "Montgomery County",
    "Sumner County",
    "Wilson County",
    "Sevier County",
    "Maury County",
    "Madison County",
    "Putnam County",
    "Robertson County",
    "Hamblen County",
    "Bradley County",
    "Tipton County",
    "Blount County",
    "Murfreesboro",
    "Collierville",
    "Bedford County",
    "Bartlett",
    "Sullivan County",
    "Washington County",
    "Dickson County",
    "Johnson City",
    "Kingsport",
    "Cumberland County",
    "Lawrence County",
    "Jefferson County",
    "Warren County",
    "Roane County",
    "Anderson County",
    "Hawkins County",
    "Greene County",
    "Germantown",
    "Union County",
    "Cheatham County",
    "Cleveland",
    "Maryville",
    "Marshall County",
    "Campbell County",
    "McMinn County",
    "Monroe County",
    "Franklin County",
    "Loudon County",
    "Johnson County",
    "Oak Ridge",
    "Arlington",
    "Carter County",
)

INDIANA_DISTRICTS: tuple[str, ...] = (
    "Fort Wayne",
    "Indianapolis Public Schools",
    "Evansville Vanderburgh",
    "Hamilton Southeastern",
    "Lawrence Township",
    "Perry Township",
    "Wayne Township",
    "Carmel Clay",
    "South Bend",
    "Vigo County",
    "Tippecanoe",
    "Warren Township",
    "Bartholomew",
    "Hammond",
    "Penn-Harris-Madison",
    "Elkhart",
    "New Albany-Floyd County",
    "Franklin Township",
    "Pike Township",
    "Noblesville",
    "Avon",
    "Washington Township",
    "Monroe County",
    "Greater Clark County",
    "Brownsburg",
    "Warrick County",
    "East Allen County",
    "Center Grove",
    "Lake Central",
    "Westfield-Washington",
    "Crown Point",
    "Northwest Allen County",
    "Southwest Allen County",
    "Lafayette",
    "Union School Corporation",
    "Portage Township",
    "Warsaw",
    "Decatur Township",
    "Valparaiso",
    "Clark-Pleasant",
    "Goshen",
    "LaPorte",
    "Anderson",
    "Merrillville",
    "Plainfield",
    "Duneland",
    "Concord",
    "Seymour",
    "Kokomo",
    "Michigan City",
)

MARYLAND_DISTRICTS: tuple[str, ...] = (
    "Montgomery County",
    "Prince George's County",
    "Baltimore County",
    "Anne Arundel County",
    "Baltimore City",
    "Howard County",
    "Frederick County",
    "Harford County",
    "Charles County",
    "Carroll County",
    "Washington County",
    "St. Mary's County",
    "Calvert County",
    "Cecil County",
    "Wicomico County",
    "Allegany County",
    "Queen Anne's County",
    "Worcester County",
    "Caroline County",
    "Dorchester County",
    "Talbot County",
    "Garrett County",
    "Somerset County",
    "Kent County",
)

MISSOURI_DISTRICTS: tuple[str, ...] = (
    "Springfield",
    "Rockwood",
    "North Kansas City",
    "Columbia",
    "St. Louis City",
    "Wentzville",
    "Lee's Summit",
    "Parkway",
    "Francis Howell",
    "Fort Zumwalt",
    "Hazelwood",
    "Blue Springs",
    "Kansas City",
    "Independence",
    "Liberty",
    "Park Hill",
    "Fox",
    "St. Joseph",
    "Mehlville",
    "Ferguson-Florissant",
    "Jefferson City",
    "Raytown",
    "Joplin",
    "Lindbergh",
    "Troy",
    "Nixa",
    "Raymore-Peculiar",
    "Kirkwood",
    "Waynesville",
    "Pattonville",
    "Ozark",
    "Northwest",
    "Jackson",
    "Ritenour",
    "Riverview Gardens",
    "Republic",
    "Poplar Bluff",
    "Hickman Mills",
    "Carthage",
    "Sedalia",
    "Neosho",
    "Fort Osage",
    "St. Charles",
    "Willard",
    "Webb City",
    "Branson",
    "Grain Valley",
    "Lebanon",
    "Ladue",
    "Webster Groves",
)

WISCONSIN_DISTRICTS: tuple[str, ...] = (
    "Milwaukee",
    "Madison",
    "Kenosha",
    "Green Bay",
    "Racine",
    "Appleton",
    "Waukesha",
    "Eau Claire",
    "Janesville",
    "Sheboygan",
    "Oshkosh",
    "Sun Prairie",
    "Wausau",
    "Elmbrook",
    "Middleton-Cross Plains",
    "West Allis-West Milwaukee",
    "Stevens Point",
    "Wauwatosa",
    "Fond du Lac",
    "Neenah",
    "Oak Creek-Franklin",
    "D.C. Everest",
    "La Crosse",
    "Verona",
    "Howard-Suamico",
    "West Bend",
    "McFarland",
    "Hudson",
    "Beloit",
    "Kimberly",
    "Hamilton",
    "Oconomowoc",
    "Mukwonago",
    "Chippewa Falls",
    "Franklin",
    "Muskego-Norway",
    "Manitowoc",
    "Wisconsin Rapids",
    "De Pere",
    "Waunakee",
    "Hortonville",
    "New Berlin",
    "Superior",
    "De Forest",
    "Oregon",
    "Kaukauna",
    "Menomonee Falls",
    "Germantown",
    "Holmen",
    "Marshfield",
)

SOUTH_CAROLINA_DISTRICTS: tuple[str, ...] = (
    "Greenville 01",
    "Charleston 01",
    "Horry 01",
    "Berkeley 01",
    "Richland 02",
    "Lexington 01",
    "Dorchester 02",
    "Aiken 01",
    "Richland 01",
    "Beaufort 01",
    "York 04",
    "Lexington 05",
    "York 03",
    "Pickens 01",
    "Florence 01",
    "Lancaster 01",
    "Sumter 01",
    "Anderson 05",
    "Spartanburg 02",
    "Spartanburg 06",
    "Kershaw 01",
    "Orangeburg",
    "Anderson 01",
    "Spartanburg 05",
    "Oconee 01",
    "York 02",
    "Darlington 01",
    "Lexington 02",
    "Greenwood 50",
    "Georgetown 01",
    "Cherokee 01",
    "Spartanburg 07",
    "Chesterfield 01",
    "Newberry 01",
    "Spartanburg 01",
    "Laurens 55",
    "York 01",
    "Colleton 01",
    "Chester 01",
    "Clarendon 06",
    "Dillon 04",
    "Marion 10",
    "Union 01",
    "Marlboro 01",
    "Lexington 04",
    "Anderson 02",
    "Edgefield 01",
    "Anderson 04",
    "Florence 03",
    "Williamsburg 01",
    "Spartanburg 04",
    "Abbeville 60",
    "Spartanburg 03",
    "Anderson 03",
    "Laurens 56",
    "Jasper 01",
    "Saluda 01",
    "Hampton",
)

ALABAMA_DISTRICTS: tuple[str, ...] = (
    "Mobile County",
    "Jefferson County",
    "Baldwin County",
    "Montgomery County",
    "Huntsville City",
    "Shelby County",
    "Birmingham City",
    "Madison County",
    "Tuscaloosa County",
    "Limestone County",
    "Hoover City",
    "Madison City",
    "Elmore County",
    "Tuscaloosa City",
    "Cullman County",
    "St Clair County",
    "Auburn City",
    "Lee County",
    "Autauga County",
    "Decatur City",
    "DeKalb County",
    "Etowah County",
    "Dothan City",
    "Lauderdale County",
    "Calhoun County",
    "Chilton County",
    "Blount County",
    "Morgan County",
    "Phenix City",
    "Talladega County",
    "Walker County",
    "Vestavia Hills City",
    "Houston County",
    "Enterprise City",
    "Alabaster City",
    "Eufaula City",
    "Marshall County",
    "Albertville City",
    "Jackson County",
    "Trussville City",
    "Opelika City",
    "Gadsden City",
    "Athens City",
    "Lawrence County",
    "Florence City",
    "Mountain Brook City",
    "Homewood City",
    "Escambia County",
    "Oxford City",
    "Pell City",
    "Cherokee County",
    "Russell County",
    "Hartselle City",
    "Franklin County",
    "Fort Payne City",
    "Pelham City",
    "Saraland City",
    "Marion County",
    "Dale County",
    "Bessemer City",
)

LOUISIANA_DISTRICTS: tuple[str, ...] = (
    "Jefferson Parish",
    "East Baton Rouge Parish",
    "St. Tammany Parish",
    "Caddo Parish",
    "Lafayette Parish",
    "Calcasieu Parish",
    "Livingston Parish",
    "Ascension Parish",
    "Bossier Parish",
    "Rapides Parish",
    "Tangipahoa Parish",
    "Ouachita Parish",
    "Terrebonne Parish",
    "Lafourche Parish",
    "St. Landry Parish",
    "Iberia Parish",
    "Vermilion Parish",
    "Acadia Parish",
    "St. Charles Parish",
    "Vernon Parish",
    "Monroe City",
    "St. Bernard Parish",
    "St. Mary Parish",
    "St. Martin Parish",
    "Beauregard Parish",
    "Zachary",
    "Lincoln Parish",
    "Evangeline Parish",
    "Jefferson Davis Parish",
    "Webster Parish",
    "Natchitoches Parish",
    "St. John the Baptist Parish",
    "Desoto Parish",
    "Avoyelles Parish",
    "Washington Parish",
    "Central",
    "Iberville Parish",
    "West Baton Rouge Parish",
    "Sabine Parish",
    "Allen Parish",
    "Plaquemines Parish",
    "St. James Parish",
    "Morehouse Parish",
    "Concordia Parish",
    "Assumption Parish",
    "Grant Parish",
    "Richland Parish",
    "Franklin Parish",
    "Pointe Coupee Parish",
    "Lasalle Parish",
    "West Feliciana Parish",
    "Jackson Parish",
    "Orleans Parish",
    "Winn Parish",
    "Bienville Parish",
    "Union Parish",
    "West Carroll Parish",
    "Bogalusa City",
    "East Feliciana Parish",
    "Claiborne Parish",
)

KENTUCKY_DISTRICTS: tuple[str, ...] = (
    "Jefferson County",
    "Fayette County",
    "Boone County",
    "Warren County",
    "Hardin County",
    "Kenton County",
    "Bullitt County",
    "Oldham County",
    "Madison County",
    "Daviess County",
    "Scott County",
    "Laurel County",
    "Jessamine County",
    "Christian County",
    "Pulaski County",
    "Pike County",
    "McCracken County",
    "Henderson County",
    "Shelby County",
    "Hopkins County",
    "Franklin County",
    "Floyd County",
    "Clark County",
    "Barren County",
    "Campbell County",
    "Owensboro",
    "Meade County",
    "Nelson County",
    "Marshall County",
    "Muhlenberg County",
    "Montgomery County",
    "Bowling Green",
    "Whitley County",
    "Carter County",
    "Grayson County",
    "Woodford County",
    "Graves County",
    "Knox County",
    "Ohio County",
    "Anderson County",
    "Covington",
    "Perry County",
    "Harlan County",
    "Grant County",
    "Logan County",
    "Rowan County",
    "Lincoln County",
    "Spencer County",
    "Johnson County",
    "Ashland",
    "Marion County",
    "Wayne County",
    "Allen County",
    "Calloway County",
    "Fort Thomas",
    "Paducah",
    "Boyd County",
    "Simpson County",
    "Corbin",
    "Russell County",
)

OREGON_DISTRICTS: tuple[str, ...] = (
    "Portland",
    "Salem-Keizer",
    "Beaverton",
    "Hillsboro",
    "Bend-La Pine",
    "North Clackamas",
    "Eugene",
    "Medford",
    "Tigard-Tualatin",
    "Gresham-Barlow",
    "Reynolds",
    "Springfield",
    "West Linn-Wilsonville",
    "Greater Albany",
    "David Douglas",
    "Oregon City",
    "Klamath County",
    "Redmond",
    "Lake Oswego",
    "McMinnville",
    "Corvallis",
    "Forest Grove",
    "Douglas County",
    "Grants Pass",
    "Centennial",
    "Hermiston",
    "Woodburn",
    "Lincoln County",
    "Bethel",
    "Sherwood",
    "Central Point",
    "Three Rivers",
    "Baker",
    "Oregon Trail",
    "Canby",
    "Eagle Point",
    "Newberg",
    "Lebanon",
    "Hood River County",
    "Silver Falls",
    "North Bend",
    "Crook County",
    "Central",
    "Estacada",
    "Coos Bay",
    "Dallas",
    "Pendleton",
    "Parkrose",
    "North Wasco County",
    "St Helens",
    "Jefferson County",
    "South Lane",
    "Klamath Falls",
    "Cascade",
    "Molalla",
    "Ashland",
    "Sweet Home",
    "Morrow",
    "Ontario",
    "Phoenix-Talent",
)

OKLAHOMA_DISTRICTS: tuple[str, ...] = (
    "Tulsa",
    "Oklahoma City",
    "Epic Virtual Charter",
    "Edmond",
    "Moore",
    "Broken Arrow",
    "Putnam City",
    "Norman",
    "Union",
    "Lawton",
    "Mustang",
    "Jenks",
    "Midwest City-Del City",
    "Owasso",
    "Yukon",
    "Bixby",
    "Enid",
    "Deer Creek",
    "Bartlesville",
    "Stillwater",
    "Choctaw-Nicoma Park",
    "Sand Springs",
    "Piedmont",
    "Muskogee",
    "Ponca City",
    "Claremore",
    "Durant",
    "Santa Fe South",
    "Sapulpa",
    "Tahlequah",
    "Coweta",
    "Altus",
    "Guthrie",
    "Duncan",
    "Shawnee",
    "Oklahoma Virtual Charter Academy",
    "Collinsville",
    "Noble",
    "Guymon",
    "McAlester",
    "El Reno",
    "Pryor",
    "Western Heights",
    "Glenpool",
    "Ada",
    "Ardmore",
    "Newcastle",
    "Grove",
    "Woodward",
    "Elgin",
    "Weatherford",
    "Chickasha",
    "Skiatook",
    "Blanchard",
    "Harrah",
    "Miami",
    "Poteau",
    "Elk City",
    "Cache",
    "Clinton",
)

COLORADO_DISTRICTS: tuple[str, ...] = (
    "Denver",
    "Jeffco",
    "Douglas County",
    "Cherry Creek",
    "Aurora",
    "Adams 12 Five Star",
    "St. Vrain Valley",
    "Poudre",
    "Boulder Valley",
    "Academy District 20",
    "Falcon",
    "Colorado Springs",
    "27J",
    "Greeley-Evans",
    "Mesa County Valley",
    "Thompson",
    "Pueblo City Schools",
    "Littleton",
    "Harrison",
    "Pueblo County",
    "Widefield",
    "Fountain-Fort Carson",
    "Westminster",
    "Mapleton",
    "Eagle County",
    "Lewis-Palmer",
    "Montrose County",
    "Roaring Fork",
    "Adams 14",
    "Byers",
    "Durango",
    "Garfield RE-2",
    "Delta County",
    "Weld RE-5J",
    "Cheyenne Mountain",
    "Summit",
    "Fort Morgan",
    "Fremont RE-1",
    "Weld RE-3J",
    "Steamboat Springs",
    "Weld RE-8",
    "Montezuma-Cortez",
    "Englewood",
    "Elizabeth",
    "Alamosa",
    "Moffat County",
    "Gunnison",
    "Woodland Park",
    "Weld RE-2",
    "Valley RE-1",
    "Weld RE-1",
    "Archuleta County",
    "Aspen",
    "Lamar",
    "Fremont RE-2",
    "Brush",
    "East Otero",
    "Salida",
    "Manitou Springs",
)

MINNESOTA_DISTRICTS: tuple[str, ...] = (
    "Anoka-Hennepin",
    "Saint Paul",
    "Rosemount-Apple Valley-Eagan",
    "Minneapolis",
    "Osseo",
    "South Washington County",
    "Rochester",
    "Elk River",
    "Wayzata",
    "Lakeville",
    "Mounds View",
    "Minnetonka",
    "Robbinsdale",
    "North St. Paul-Maplewood-Oakdale",
    "Bloomington",
    "Eastern Carver County",
    "St. Cloud",
    "Eden Prairie",
    "Prior Lake-Savage",
    "Edina",
    "Duluth",
    "White Bear Lake",
    "Mankato",
    "Stillwater",
    "Shakopee",
    "Burnsville-Eagan-Savage",
    "Moorhead",
    "Roseville",
    "Hopkins",
    "Farmington",
    "Centennial",
    "St. Michael-Albertville",
    "Brainerd",
    "Spring Lake Park",
    "Forest Lake",
    "Buffalo-Hanover-Montrose",
    "Austin",
    "West St. Paul-Mendota Heights-Eagan",
    "Cambridge-Isanti",
    "Owatonna",
    "Minnesota Transitions Charter",
    "Bemidji",
    "St. Louis Park",
    "Sauk Rapids-Rice",
    "St. Francis",
    "Willmar",
    "New Prague",
    "Monticello",
    "Richfield",
    "Hastings",
    "Sartell-St. Stephen",
    "Alexandria",
    "Waconia",
    "Grand Rapids",
    "Northfield",
    "Albert Lea",
    "Inver Grove Heights",
    "Chisago Lakes",
    "Worthington",
    "Princeton",
)

NEVADA_DISTRICTS: tuple[str, ...] = (
    "Clark County",
    "Washoe County",
    "Elko County",
    "Lyon County",
    "Carson City",
    "Nye County",
    "Douglas County",
    "Churchill County",
    "Humboldt County",
    "White Pine County",
    "Lander County",
    "Lincoln County",
    "Pershing County",
    "Mineral County",
    "Storey County",
    "Eureka County",
    "Davidson Academy",
    "Esmeralda County",
)

UTAH_DISTRICTS: tuple[str, ...] = (
    "Alpine District",
    "Davis District",
    "Granite District",
    "Jordan District",
    "Washington District",
    "Nebo District",
    "Canyons District",
    "Weber District",
    "Tooele District",
    "Cache District",
    "Salt Lake District",
    "Provo District",
    "Iron District",
    "Box Elder District",
    "Ogden City District",
    "Wasatch District",
    "Uintah District",
    "Murray District",
    "Duchesne District",
    "Logan City District",
    "American Preparatory Academy",
    "Sevier District",
    "Park City District",
    "Carbon District",
    "Morgan District",
    "South Sanpete District",
    "Millard District",
    "San Juan District",
    "North Sanpete District",
    "Juab District",
    "Ascent Academies of Utah",
    "Emery District",
    "Providence Hall",
    "Freedom Preparatory Academy",
    "Summit Academy",
    "Utah Virtual Academy",
    "Syracuse Arts Academy",
    "South Summit District",
    "American Leadership Academy",
    "Spectrum Academy",
    "Beaver District",
    "Kane District",
    "Grand District",
    "Excelsior Academy",
    "Hawthorn Academy",
    "Wallace Stegner Academy",
    "Garfield District",
    "Thomas Edison",
    "Davinci Academy",
    "No. Ut. Acad. for Math Engineering & Science",
    "Vista School",
    "Monticello Academy",
    "Entheos Academy",
    "North Summit District",
    "Ogden Preparatory Academy",
    "Utah Connections Academy",
    "Quest Academy",
    "Lakeview Academy",
    "George Washington Academy",
    "Early Light Academy at Daybreak",
)

STATE_DISTRICTS: dict[str, tuple[str, ...]] = {
    "Alabama": ALABAMA_DISTRICTS,
    "Arizona": ARIZONA_DISTRICTS,
    "California": CALIFORNIA_DISTRICTS,
    "Colorado": COLORADO_DISTRICTS,
    "Connecticut": CONNECTICUT_DISTRICTS,
    "Florida": FLORIDA_DISTRICTS,
    "Georgia": GEORGIA_DISTRICTS,
    "Illinois": ILLINOIS_DISTRICTS,
    "Indiana": INDIANA_DISTRICTS,
    "Kentucky": KENTUCKY_DISTRICTS,
    "Louisiana": LOUISIANA_DISTRICTS,
    "Maryland": MARYLAND_DISTRICTS,
    "Massachusetts": MASSACHUSETTS_DISTRICTS,
    "Michigan": MICHIGAN_DISTRICTS,
    "Minnesota": MINNESOTA_DISTRICTS,
    "Missouri": MISSOURI_DISTRICTS,
    "Nevada": NEVADA_DISTRICTS,
    "New Jersey": NEW_JERSEY_DISTRICTS,
    "New York": NEW_YORK_DISTRICTS,
    "North Carolina": NORTH_CAROLINA_DISTRICTS,
    "Ohio": OHIO_DISTRICTS,
    "Oklahoma": OKLAHOMA_DISTRICTS,
    "Oregon": OREGON_DISTRICTS,
    "Pennsylvania": PENNSYLVANIA_DISTRICTS,
    "South Carolina": SOUTH_CAROLINA_DISTRICTS,
    "Tennessee": TENNESSEE_DISTRICTS,
    "Texas": TEXAS_DISTRICTS,
    "Utah": UTAH_DISTRICTS,
    "Virginia": VIRGINIA_DISTRICTS,
    "Washington": WASHINGTON_DISTRICTS,
    "Wisconsin": WISCONSIN_DISTRICTS,
}

STATE_ABBREVIATIONS: dict[str, str] = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

# Substrings in URL/title/header that strongly indicate a page is from another state
_STATE_CONFLICT_HINTS: dict[str, tuple[str, ...]] = {
    "Connecticut": (
        "new york city",
        "city of new york",
        "nyc.gov",
        "schools.nyc",
        "/nyc/",
        "new york, ny",
        "state of new york",
        ".ny.us",
        "k12.ny",
        "massachusetts",
        ".ma.us",
        "k12.ma",
        "new jersey",
        ".nj.us",
        "k12.nj",
        "rhode island",
        ".ri.us",
        "k12.ri",
    ),
}

# US area codes by state — used to detect out-of-state pages from phone numbers
STATE_AREA_CODES: dict[str, frozenset[str]] = {
    "Connecticut": frozenset({"203", "475", "860", "959"}),
    "New Jersey": frozenset({"201", "551", "609", "640", "732", "848", "856", "862", "908", "973"}),
    "New York": frozenset({"212", "315", "332", "347", "516", "518", "585", "607", "631", "646", "680", "716", "718", "838", "845", "914", "917", "929", "934"}),
    "Massachusetts": frozenset({"339", "351", "413", "508", "617", "774", "781", "857", "978"}),
    "Rhode Island": frozenset({"401"}),
}


def get_area_codes_for_state(state: str) -> frozenset[str]:
    """Return known area codes for a state."""
    return STATE_AREA_CODES.get(state, frozenset())


def get_districts_for_state(state: str) -> list[str]:
    """Return the static district name list for a state, or an empty list."""
    districts = STATE_DISTRICTS.get(state)
    if not districts:
        return []
    return list(districts)


def get_conflict_hints_for_state(state: str) -> tuple[str, ...]:
    """Return substrings that suggest a page belongs to a different state."""
    return _STATE_CONFLICT_HINTS.get(state, ())


def state_abbreviation(state: str) -> str:
    """Return the postal abbreviation for a state name, or the name itself."""
    return STATE_ABBREVIATIONS.get(state, state)
