"""
Static reference lists of K-12 school districts by state.

Used to generate targeted per-district search queries that surface staff
directory pages more reliably than generic state-level search phrasing alone.
"""

from __future__ import annotations

# Town and regional district names for Connecticut (~169 municipalities plus
# regional school districts). Search queries use the short town/district name
# (e.g. "Brookfield") rather than the full legal district name.
CONNECTICUT_DISTRICTS: tuple[str, ...] = (
    "Andover",
    "Ansonia",
    "Ashford",
    "Avon",
    "Barkhamsted",
    "Berlin",
    "Bethany",
    "Bethel",
    "Bethlehem",
    "Bloomfield",
    "Bolton",
    "Bozrah",
    "Branford",
    "Bridgeport",
    "Bridgewater",
    "Bristol",
    "Brookfield",
    "Brooklyn",
    "Burlington",
    "Canaan",
    "Canterbury",
    "Canton",
    "Chaplin",
    "Cheshire",
    "Chester",
    "Clinton",
    "Colchester",
    "Colebrook",
    "Columbia",
    "Cornwall",
    "Coventry",
    "Cromwell",
    "Danbury",
    "Darien",
    "Deep River",
    "Derby",
    "Durham",
    "East Granby",
    "East Haddam",
    "East Hampton",
    "East Hartford",
    "East Lyme",
    "East Windsor",
    "Easton",
    "Ellington",
    "Enfield",
    "Essex",
    "Fairfield",
    "Farmington",
    "Franklin",
    "Glastonbury",
    "Goshen",
    "Granby",
    "Greenwich",
    "Griswold",
    "Groton",
    "Guilford",
    "Haddam",
    "Hamden",
    "Hampton",
    "Hartford",
    "Hartland",
    "Harwinton",
    "Hebron",
    "Kent",
    "Killingly",
    "Killingworth",
    "Lebanon",
    "Ledyard",
    "Lisbon",
    "Litchfield",
    "Lyme",
    "Madison",
    "Manchester",
    "Mansfield",
    "Marlborough",
    "Meriden",
    "Middlebury",
    "Middletown",
    "Milford",
    "Monroe",
    "Montville",
    "Morris",
    "Naugatuck",
    "New Britain",
    "New Canaan",
    "New Fairfield",
    "New Hartford",
    "New Haven",
    "New London",
    "New Milford",
    "Newington",
    "Newtown",
    "Norfolk",
    "North Branford",
    "North Canaan",
    "North Haven",
    "North Stonington",
    "Norwalk",
    "Norwich",
    "Old Lyme",
    "Old Saybrook",
    "Orange",
    "Oxford",
    "Plainfield",
    "Plainville",
    "Plymouth",
    "Pomfret",
    "Portland",
    "Preston",
    "Prospect",
    "Putnam",
    "Redding",
    "Ridgefield",
    "Rocky Hill",
    "Roxbury",
    "Salem",
    "Salisbury",
    "Scotland",
    "Seymour",
    "Sharon",
    "Shelton",
    "Sherman",
    "Simsbury",
    "Somers",
    "South Windsor",
    "Southbury",
    "Southington",
    "Sprague",
    "Stafford",
    "Stamford",
    "Stonington",
    "Stratford",
    "Suffield",
    "Thomaston",
    "Thompson",
    "Tolland",
    "Torrington",
    "Trumbull",
    "Union",
    "Vernon",
    "Voluntown",
    "Wallingford",
    "Warren",
    "Washington",
    "Waterbury",
    "Waterford",
    "Watertown",
    "West Hartford",
    "West Haven",
    "Westbrook",
    "Weston",
    "Westport",
    "Wethersfield",
    "Willington",
    "Wilton",
    "Winchester",
    "Windham",
    "Windsor",
    "Windsor Locks",
    "Wolcott",
    "Woodbridge",
    "Woodbury",
    "Woodstock",
    "Regional School District 1",
    "Regional School District 4",
    "Regional School District 5",
    "Regional School District 7",
    "Regional School District 8",
    "Regional School District 9",
    "Regional School District 10",
    "Regional School District 11",
    "Regional School District 12",
    "Regional School District 13",
    "Regional School District 14",
    "Regional School District 15",
    "Regional School District 16",
    "Regional School District 17",
    "Regional School District 18",
    "Regional School District 19",
    "Regional School District 20",
)

STATE_DISTRICTS: dict[str, tuple[str, ...]] = {
    "Connecticut": CONNECTICUT_DISTRICTS,
}

STATE_ABBREVIATIONS: dict[str, str] = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

# Substrings in URL/title/header that strongly indicate a page is from another state
_STATE_CONFLICT_HINTS: dict[str, tuple[str, ...]] = {
    "Connecticut": (
        "new york city",
        "city of new york",
        "nyc.gov",
        "schools.nyc",
        "/nyc/",
        "new york, ny",
        "state of new york",
        ".ny.us",
        "k12.ny",
        "massachusetts",
        ".ma.us",
        "k12.ma",
        "new jersey",
        ".nj.us",
        "k12.nj",
        "rhode island",
        ".ri.us",
        "k12.ri",
    ),
}

# US area codes by state — used to detect out-of-state pages from phone numbers
STATE_AREA_CODES: dict[str, frozenset[str]] = {
    "Connecticut": frozenset({"203", "475", "860", "959"}),
    "New Jersey": frozenset({"201", "551", "609", "640", "732", "848", "856", "862", "908", "973"}),
    "New York": frozenset({"212", "315", "332", "347", "516", "518", "585", "607", "631", "646", "680", "716", "718", "838", "845", "914", "917", "929", "934"}),
    "Massachusetts": frozenset({"339", "351", "413", "508", "617", "774", "781", "857", "978"}),
    "Rhode Island": frozenset({"401"}),
}


def get_area_codes_for_state(state: str) -> frozenset[str]:
    """Return known area codes for a state."""
    return STATE_AREA_CODES.get(state, frozenset())


def get_districts_for_state(state: str) -> list[str]:
    """Return the static district name list for a state, or an empty list."""
    districts = STATE_DISTRICTS.get(state)
    if not districts:
        return []
    return list(districts)


def get_conflict_hints_for_state(state: str) -> tuple[str, ...]:
    """Return substrings that suggest a page belongs to a different state."""
    return _STATE_CONFLICT_HINTS.get(state, ())


def state_abbreviation(state: str) -> str:
    """Return the postal abbreviation for a state name, or the name itself."""
    return STATE_ABBREVIATIONS.get(state, state)
